spring:
  application:
    name: board
  datasource:
    hikari:
      jdbc-url: jdbc:h2:tcp://localhost/C:/workspace/11_SpringBoot/board/tdb
      driver-class-name: org.h2.Driver
      username: sa
      password:
  h2:
    console:
      enabled: true
      path: /h2-console
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true

server:
  port: 8888

  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

mybatis:
  type-aliases-package: com.kh.board.entity
  mapper-locations: mappers/*.xml